[package]
name = "email-auth"
version = "0.1.0"
edition = "2021"
rust-version = "1.80"

[dependencies]
hickory-resolver = "0.25"
ring = "0.17"
base64 = "0.22"
thiserror = "2"
tokio = { version = "1", features = ["rt-multi-thread"] }
rand = "0.9"
psl = "2.1.187"

[dev-dependencies]
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }
